---
micronaut:
    application:
        name: server
    router:
      static-resources:
          default:
            mapping: /**
            paths: classpath:public
datasources:
  default:
    url: jdbc:sqlite:questioneer-devel.sqlite
    driverClassName: org.sqlite.JDBC
    username: ''
    password: ''    
jpa:
  default:
    #packages-to-scan:
    #  - 'server.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.SQLiteDialect


---
#datasources.default: {}